version: '2'
services:
  web:
    build:
      context: ../../
      dockerfile: ci/prod/Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      - MIX_ENV=prod
      - HOST=0.0.0.0
      - PORT=4000
      - POSTGRES_HOSTNAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=heart_prod
      - POSTGRES_PORT=5432
  postgres:
    image: postgres:9.6.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      # - POSTGRES_DB=heart_prod

