version: '2'
services:
  postgres:
    image: postgres:9.6.1
    ports:
      - "5432:5432"
    volumes:
      - ../../data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=heart_dev
